GET http://localhost:3003/api/users
Content-Type: application/json

###


POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "ozgur",
    "name": "ozgur",
    "password": "ozgur"
}